import { describe, expect, it } from "vitest";
import type { Env } from "../src/env";
import { searchCapabilities } from "../src/search";

const offlineEnv = { SEARCH_OFFLINE: "true" } as Env;

const goldenQueries = [
	["who am i", "whoami"],
	["what can you do", "overview"],
	["list everything you can do", "capabilities_list"],
	["show my profile", "whoami"],
	["show available tools", "capabilities_list"],
	["browse the capability registry", "capabilities_list"],
	["write this down", "notebook_write"],
	["save this note as a draft page", "notebook_write"],
	["read the brief", "notebook_read"],
	["open a notebook page", "notebook_read"],
	["show me my notes", "notebook_list"],
	["list all notebook pages", "notebook_list"],
	["recent notes", "notebook_list"],
	["delete this notebook page", "notebook_delete"],
	["remove that notebook page", "notebook_delete"],
	["what did the brief say before", "notebook_history"],
	["show the page history", "notebook_history"],
	["remember that i prefer aisle seats", "memory_remember"],
	["save my dietary preference for later", "memory_remember"],
	["what do you know about my travel preferences", "memory_recall"],
	["recall my seat preference", "memory_recall"],
	["forget what i said about aisle seats", "memory_forget"],
	["remove this fact from memory", "memory_forget"],
	["which email accounts do you have", "accounts_list"],
	["list my mail accounts", "accounts_list"],
	["which email tags exist", "email_tags"],
	["make a new tag for receipts", "email_tag_create"],
	["add an email tag", "email_tag_create"],
	["rename the receipts tag", "email_tag_update"],
	["change the tag color", "email_tag_update"],
	["delete the receipts tag", "email_tag_delete"],
	["remove that mail label", "email_tag_delete"],
	["list my mail labels", "email_tags"],
	["find messages in my inbox", "email_search"],
	["show my starred email", "email_search"],
	["read this email thread", "email_read"],
	["show me the full message body", "email_read"],
	["compose a new email", "email_draft"],
	["prepare an email reply without sending", "email_draft"],
	["send the reviewed email draft", "email_send"],
	["deliver this draft now", "email_send"],
	["move this email to archive", "email_move"],
	["file this message in another folder", "email_move"],
	["star this email message", "email_flag"],
	["tag this email as receipts", "email_flag"],
	["apply the work label to this message", "email_flag"],
	["mark this message as unread", "email_flag"],
	["list my calendars", "calendar_calendars"],
	["which calendars can i use", "calendar_calendars"],
	["create a new calendar for a project", "calendar_create"],
	["add a separate calendar", "calendar_create"],
	["what is on my calendar this week", "calendar_events"],
	["show my appointments between monday and friday", "calendar_events"],
	["open this calendar event", "calendar_event_read"],
	["show the details for this appointment", "calendar_event_read"],
	["add a meeting tomorrow at 10", "calendar_event_create"],
	["schedule a dentist appointment", "calendar_event_create"],
	["move my meeting to 11", "calendar_event_update"],
	["change this calendar event", "calendar_event_update"],
	["cancel my dentist appointment", "calendar_event_delete"],
	["delete this calendar event", "calendar_event_delete"],
	["what tasks are due this week", "task_list"],
	["what is on my plate", "task_list"],
	["show my overdue tasks", "task_list"],
	["open this task and show its details", "task_read"],
	["read this to-do item", "task_read"],
	["add a task to buy groceries", "task_create"],
	["remember to renew my passport", "task_create"],
	["put renew passport on my task list", "task_create"],
	["mark the groceries task as done", "task_update"],
	["change the due date for this task", "task_update"],
	["drop that task", "task_delete"],
	["delete this to-do item", "task_delete"],
	["what is timi's email address", "contact_find"],
	["look up a phone number in my address book", "contact_find"],
	["open the full contact card", "contact_read"],
	["add timi to my contacts", "contact_create"],
	["save a new person to my address book", "contact_create"],
	["remove timi from my contacts", "contact_delete"],
	["delete this contact", "contact_delete"],
	["run this script every morning at 8", "job_create"],
	["schedule an unattended cron job", "job_create"],
	["when an email arrives tag it", "job_create"],
	["run this when new mail comes in", "job_create"],
	["what jobs are scheduled", "job_list"],
	["list my recurring automations", "job_list"],
	["inspect this scheduled job", "job_read"],
	["show me the code for this job", "job_read"],
	["pause that job", "job_update"],
	["change the schedule for this automation", "job_update"],
	["delete the daily brief job", "job_delete"],
	["remove this scheduled automation", "job_delete"],
	["run the job now", "job_run_now"],
	["execute this scheduled script immediately", "job_run_now"],
	["run a model on this text", "ai_run"],
	["classify this with an llm", "ai_run"],
	["summarize this using ai", "ai_run"],
] as const;

describe("capability search golden queries", () => {
	it.each(goldenQueries)("%s", async (query, expected) => {
		const result = await searchCapabilities(query, offlineEnv);
		if (expected === "overview") {
			expect(result).toHaveProperty("domains");
			return;
		}

		const ranked = result as { matches: Array<{ name: string }> };
		expect(ranked.matches[0]?.name).toBe(expected);
		expect(ranked).toMatchObject({ offline: true });
	});
});
