import { describe, expect, it } from "vitest";
import type { Env } from "../src/env";
import { searchCapabilities } from "../src/search";

const offlineEnv = { SEARCH_OFFLINE: "true" } as Env;

// Each pair must be won on score, not on registry order. A phrasing that only
// ties and resolves by declaration order is false coverage: it passes for the
// whole calibrated band of STOPWORD_WEIGHT and flips when a capability is added
// above it. Verify a new pair by moving its capability to the end of its domain
// array and confirming the test still passes.
const goldenQueries = [
	["who am i", "whoami"],
	["what can you do", "overview"],
	["list everything you can do", "capabilities_list"],
	["show my profile", "whoami"],
	["show available tools", "capabilities_list"],
	["browse the capability registry", "capabilities_list"],
	["write this down", "notebook_write"],
	["save this note as a draft page", "notebook_write"],
	["read the brief", "notebook_read"],
	["open a notebook page", "notebook_read"],
	["show me my notes", "notebook_list"],
	["list all notebook pages", "notebook_list"],
	["recent notes", "notebook_list"],
	["delete this notebook page", "notebook_delete"],
	["remove that notebook page", "notebook_delete"],
	["what did the brief say before", "notebook_history"],
	["show the page history", "notebook_history"],
	["remember that i prefer aisle seats", "memory_remember"],
	["save my dietary preference for later", "memory_remember"],
	["what do you know about my travel preferences", "memory_recall"],
	["recall my seat preference", "memory_recall"],
	["forget what i said about aisle seats", "memory_forget"],
	["remove this fact from memory", "memory_forget"],
	["search my documents for the tax receipt", "document_search"],
	["find documents by name", "document_search"],
	["list documents in the taxes folder", "document_search"],
	["who sends me documents", "document_correspondents"],
	["list my document correspondents", "document_correspondents"],
	["open this document and show its ocr text", "document_read"],
	["read the full metadata for this document", "document_read"],
	["set the correspondent on this document", "document_update"],
	["update this document's metadata", "document_update"],
	["move this document into the taxes folder", "document_move"],
	["file this document in another folder", "document_move"],
	["delete this document", "document_trash"],
	["send this document to the trash", "document_trash"],
	["restore this document from the trash", "document_restore"],
	["undelete this document", "document_restore"],
	["retry ocr on this document", "document_retry_processing"],
	["this document's processing failed, try again", "document_retry_processing"],
	["what document folders do i have", "document_folders"],
	["list my document archive folders", "document_folders"],
	["create a new document folder", "document_folder_create"],
	["add a folder for tax documents", "document_folder_create"],
	["rename this document folder", "document_folder_update"],
	["change this document folder's parent", "document_folder_update"],
	["delete this document folder", "document_folder_delete"],
	["remove this document folder", "document_folder_delete"],
	["which document tags exist", "document_tags"],
	["list my document tags", "document_tags"],
	["create a new document tag", "document_tag_create"],
	["add a document tag", "document_tag_create"],
	["rename this document tag", "document_tag_update"],
	["change this document tag's name", "document_tag_update"],
	["delete this document tag", "document_tag_delete"],
	["remove a document tag", "document_tag_delete"],
	["tag this document", "document_tags_update"],
	["untag this document", "document_tags_update"],
	["replace the tags on this document", "document_tags_set"],
	["remove all tags from this document", "document_tags_set"],
	["upload this pdf to my documents", "document_upload"],
	["add this local file to the archive", "document_upload"],
	["run ocr on a pdf from my laptop", "ocr_extract"],
	["extract the text from a scanned pdf", "ocr_extract"],
	["what is written in this scanned letter", "ocr_extract"],
	["get the words out of this phone picture of a receipt", "ocr_extract"],
	["download this document's original file", "document_file"],
	["get the document file", "document_file"],
	["which email accounts do you have", "accounts_list"],
	["list my mail accounts", "accounts_list"],
	["list my mail folders", "email_mailboxes"],
	["which folder is my archive", "email_mailboxes"],
	["what are my mail folders", "email_mailboxes"],
	["what mail folders do i have", "email_mailboxes"],
	["create a mail folder", "email_mailbox_create"],
	["make a new mailbox", "email_mailbox_create"],
	["rename this folder", "email_mailbox_rename"],
	["change this mailbox name", "email_mailbox_rename"],
	["delete an empty folder", "email_mailbox_delete"],
	["remove this empty mailbox", "email_mailbox_delete"],
	["which email tags exist", "email_tags"],
	["make a new tag for receipts", "email_tag_create"],
	["add an email tag", "email_tag_create"],
	["rename the receipts tag", "email_tag_update"],
	["change the tag color", "email_tag_update"],
	["delete the receipts tag", "email_tag_delete"],
	["remove that mail label", "email_tag_delete"],
	["list my mail labels", "email_tags"],
	["find messages in my inbox", "email_search"],
	["show messages with the receipts tag", "email_search"],
	["show my starred email", "email_search"],
	["read this email thread", "email_read"],
	["show me the full message body", "email_read"],
	["compose a new email", "email_draft"],
	["prepare an email reply without sending", "email_draft"],
	["send the reviewed email draft", "email_send"],
	["deliver this draft now", "email_send"],
	["move this email to archive", "email_move"],
	["file this message in another folder", "email_move"],
	["star this email message", "email_flag"],
	["tag this email as receipts", "email_flag"],
	["apply the work label to this message", "email_flag"],
	["mark this message as unread", "email_flag"],
	["list my calendars", "calendar_calendars"],
	["which calendars can i use", "calendar_calendars"],
	["create a new calendar for a project", "calendar_create"],
	["add a separate calendar", "calendar_create"],
	["what is on my calendar this week", "calendar_events"],
	["show my appointments between monday and friday", "calendar_events"],
	["open this calendar event", "calendar_event_read"],
	["show the details for this appointment", "calendar_event_read"],
	["add a meeting tomorrow at 10", "calendar_event_create"],
	["schedule a dentist appointment", "calendar_event_create"],
	["move my meeting to 11", "calendar_event_update"],
	["change this calendar event", "calendar_event_update"],
	["cancel my dentist appointment", "calendar_event_delete"],
	["delete this calendar event", "calendar_event_delete"],
	["what tasks are due this week", "task_list"],
	["what is on my plate", "task_list"],
	["show my overdue tasks", "task_list"],
	["show my completed tasks", "task_list"],
	["open this task and show its details", "task_read"],
	["read this to-do item", "task_read"],
	["add a task to buy groceries", "task_create"],
	["remember to renew my passport", "task_create"],
	["put renew passport on my task list", "task_create"],
	["create a daily recurring task", "task_create"],
	["mark the groceries task as done", "task_update"],
	["change the due date for this task", "task_update"],
	["drop that task", "task_delete"],
	["delete this to-do item", "task_delete"],
	["list my contact address books", "contact_addressbooks"],
	["show available address books", "contact_addressbooks"],
	["what is timi's email address", "contact_find"],
	["look up a phone number in my address book", "contact_find"],
	["open the full contact card", "contact_read"],
	["add timi to my contacts", "contact_create"],
	["save a new person to my address book", "contact_create"],
	["change timi's phone number", "contact_update"],
	["edit this contact's job title", "contact_update"],
	["remove timi from my contacts", "contact_delete"],
	["delete this contact", "contact_delete"],
	["find everyone tagged family in my contacts", "contact_find"],
	["which contact groups do i have", "contact_group_list"],
	["show my distribution lists", "contact_group_list"],
	["who is in the family group", "contact_group_read"],
	["list the members of this contact group", "contact_group_read"],
	["create a contact group for the project team", "contact_group_create"],
	["make a new group of contacts", "contact_group_create"],
	["add timi to the family group", "contact_group_update"],
	["remove someone from this contact group", "contact_group_update"],
	["delete the old project contact group", "contact_group_delete"],
	["remove this group but keep the people", "contact_group_delete"],
	["what arguments does a bureau event receive", "job_event_catalog"],
	["show the payload for account.created", "job_event_catalog"],
	["what fields are available to an event-triggered job", "job_event_catalog"],
	["run this script every morning at 8", "job_create"],
	["schedule an unattended cron job", "job_create"],
	["when an email arrives tag it", "job_create"],
	["run this when new mail comes in", "job_create"],
	["what jobs are scheduled", "job_list"],
	["list my recurring automations", "job_list"],
	["inspect this scheduled job", "job_read"],
	["show me the code for this job", "job_read"],
	["show more of this job's run history", "job_read"],
	["pause that job", "job_update"],
	["change the schedule for this automation", "job_update"],
	["delete the daily brief job", "job_delete"],
	["remove this scheduled automation", "job_delete"],
	["run the job now", "job_run_now"],
	["execute this scheduled script immediately", "job_run_now"],
	["file a github issue for this bug", "github_issue_create"],
	["open a github ticket for this failed automation", "github_issue_create"],
	["list the open github issues", "github_issue_list"],
	["show the bugs ayo already reported", "github_issue_list"],
	["read this github issue and its comments", "github_issue_get"],
	["show the details for github issue 12", "github_issue_get"],
	["comment on this github issue", "github_issue_comment"],
	["add a follow-up to the github ticket", "github_issue_comment"],
	["list my migadu hosted domains", "migadu_domains"],
	["what custom email domains have i onboarded", "migadu_domains"],
	["onboard a new domain to migadu", "migadu_domain_create"],
	["set up email hosting for a new custom domain", "migadu_domain_create"],
	["what dns records does migadu need for this domain", "migadu_domain_records"],
	["show the mx and spf records to add at the registrar", "migadu_domain_records"],
	["check the dns diagnostics for this migadu domain", "migadu_domain_diagnostics"],
	["run a dns health check for this migadu domain", "migadu_domain_diagnostics"],
	["activate this migadu domain", "migadu_domain_activate"],
	["finish setting up this migadu domain now that dns is live", "migadu_domain_activate"],
	["list the email addresses on this migadu domain", "migadu_mailboxes"],
	["show the mailboxes hosted on this custom domain", "migadu_mailboxes"],
	["create a new email address on my migadu domain", "migadu_mailbox_create"],
	["add a new address to my migadu account", "migadu_mailbox_create"],
	["list the email aliases on this migadu domain", "migadu_aliases"],
	["what forwarding addresses exist on this migadu domain", "migadu_aliases"],
	["create an email alias that forwards to another address", "migadu_alias_create"],
	["set up an alias on my migadu domain that forwards mail", "migadu_alias_create"],
	["delete this email alias", "migadu_alias_delete"],
	["remove this forwarding address", "migadu_alias_delete"],
	["run a model on this text", "ai_run"],
	["classify this with an llm", "ai_run"],
	["summarize this using ai", "ai_run"],
] as const;

describe("capability search golden queries", () => {
	it.each(goldenQueries)("%s", async (query, expected) => {
		const result = await searchCapabilities(query, offlineEnv);
		if (expected === "overview") {
			expect(result).toHaveProperty("domains");
			return;
		}

		const ranked = result as { matches: Array<{ name: string }> };
		expect(ranked.matches[0]?.name).toBe(expected);
		expect(ranked).toMatchObject({ offline: true });
	});
});
